### ISSUE TITLE
Full adoption of JSON-LD

### ISSUE THREAD

**Issue by jbohrer** [openbadges/openbadges-specification#101]
The intention of this issue is to explicitly request the full adoption of JSON-LD as the data model for OB 2.0.

As an issuer, I would like to fully adopt the JSON-LD data model and syntax so that I can:
- Define achievements so that they may be understood more broadly in search engines and other applications embedding Semantic Web principles via the use of JSON-LD.
- Publish achievement definitions (BadgeClasses) in a format that allows other web services to find and understand my badge offerings.
- Embed badge objects within one another and have badges embedded in other JSON-LD documents within and beyond the Open Badges Specification. See also #82.
- Issue a single badge in a variety of languages according to learner choice. See also #1.
- Publish badge objects in languages other than English and in multiple languages, tagging these languages with a widely recognized mechanism already deployed on the web. See also #1.

As an inspector of badges, I would like these objects published in JSON-LD, so I can:
- Transform these representations using off-the-shelf tools designed for working with data in this format.
- Understand the links between entities, and the badges they award or receive.
- Be able to build my own documents that contain badge data without losing any of the meaning of the original publication formats.

**Comment by mgylling** [comment]
Closing this issue as it was resolved by the 2.0 recommendation.
