### ISSUE TITLE
Audit Extensions Page for 2.0 Examples

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#118]
Extensions page should be updated to use examples that match the 2.0 spec. This may or may not be done yet.

**Comment by sgance** [comment]
Under http://openbadgespec.org/extensions/, Creative Commons Content License, Extendable Badge Objects: BadgeClass
•	“@context” : https://openbadgespec.org/v1   <--- should be v2

**Comment by mtmercury** [comment]
One issue was discovered. The @context URL in the Creative Commons extensions example references v1 not v2.

{
  "@context": "https://w3id.org/openbadges/**v1**",
  "type": "BadgeClass",
  "name": "Licensed Badge",
  "...": "...",
  "schema:license": {
    "@context": "https://openbadgespec.org/extensions/licenseExtension/context.json",
    "type": ["Extension", "extensions:LicenseExtension", "cc:License"],
    "id": "CC-BY",
    "name": "Creative Commons Attribution",
    "legalCode": "http://creativecommons.org/licenses/by/4.0/legalcode"
  }
}

**Comment by mgylling** [comment]
Fixed by #127
