### ISSUE TITLE
Review extensions page prose

### ISSUE THREAD

**Issue by mgylling** [openbadges/openbadges-specification#130]
Review extensions page intro prose to make sure it is 100% clear that the referenced extensions specs are not part of the normative specification, and that no guarantees are given regarding the IP status, licensing etc.

**Comment by ottonomy** [comment]
> no guarantees are given regarding the IP status, licensing etc.

In regard to licensing, while we can't offer a guarantee that other prior IP may undercut such a license, I would like to be explicitly clear from the authors of these extensions that by including them on the page, they are releasing them for free public use under the same license as the specification. The number of authors is small -- we should be able to get confirmation from them all that this is suitable. I don't think this is clearly enough spelled out as it is.

**Comment by mgylling** [comment]
Right, good point. It was not clear to me either after reading the page frontmatter that same-licensing was the idea.

**Comment by jbohrer** [comment]
Recommended statement:
"These extensions are not part of the core specification and are governed by licensing and copyright terms of the authoring individuals and organizations."

**Comment by mgylling** [comment]
Fixed in adac761. 

https://github.com/openbadges/openbadges-specification/commit/adac76113af5a9fa4d3bc229087f8cabbe661bfe
