### ISSUE TITLE
Two DOM elements with id=verification in spec document

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#136]
The section about Verification under implementation should be given a new element id other than "verification". Perhaps: "implementation-verification".

See https://openbadgespec.org/#verification

This will ensure that the id in the vocabulary for the verification term is not ambiguous and also allow community members to link directly to the Verification section of the document to describe the process.

**Comment by jbohrer** [comment]
@ottonomy to clarify, you are suggesting _adding_ an element id (vs. replacing something that already exists), right? If I'm looking in the right location, I do not see a current element id on the "Verification" section under "Implementation".

**Comment by jbohrer** [comment]
See [PR #138](https://github.com/openbadges/openbadges-specification/pull/138)

**Comment by ottonomy** [comment]
Yes, @jbohrer -- It looks like Jekyll was auto-generating an id that matched another one in the document for the H2 in question. PR #138 solves that issue.

**Comment by mgylling** [comment]
Resolved by #138.
