### ISSUE TITLE
Fix link to schema.json in Issuer Accreditation extension

### ISSUE THREAD

**Issue by jbohrer** [openbadges/openbadges-specification#141]
In the Issuer Accreditation Extension, the URL to the schema.json file contains a typo:

Incorrect: https://openbadgespec.org/extensions/issuerAccreditation/schema.json
Correct: https://openbadgespec.org/extensions/issuerAccreditationExtension/schema.json

**Comment by jbohrer** [comment]
Issue is located in the context.json file.

Fixed by PR #142

**Comment by mgylling** [comment]
Resolved by #142.
