### ISSUE TITLE
Primitive Datatypes doesn't specify

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#143]
This is a missed issued from previous versions of the text. It is a clarification, but it should qualify as an in-place edit.

https://openbadgespec.org/#primitive-datatypes does not say what hash mechanisms are supported or what string identifiers are used to identify them.

The supported algs are MD5 and SHA-256, identified by `md5` and `sha256`. 

In my opinion, these hashes (single-pass) are not seen as protection against serious deanonymization attacks and the use of the slightly old MD5 library is not a security issue.

**Comment by timothyfcook** [comment]
👍
