### ISSUE TITLE
Incomplete sentence on Revocation

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#144]
There is a short sentence in the explanation for [RevocationList](http://openbadgespec.org/#RevocationList): "If the issuer does not wish to declare a revocation reason or additional metadata, the"

This sentence should read:
"If the issuer does not wish to declare a revocation reason or additional metadata, the `id` of the Assertion may be included alone either as a single string entry to the list or in an object that defines an `id` property.

**Comment by jbohrer** [comment]
Good catch. I support fixing this and publishing the change asap.
