### ISSUE TITLE
BadgeClass alignment is required to be an Array/List. Necessary?

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#145]
There's a bit of a holdover from our pre-JSON-LD days here: [BadgeClass](https://openbadgespec.org#BadgeClass) says for its `alignment` property...

|  property  |  type  |  rules  |
|-|-|-|
alignment | Array of AlignmentObjects |List of objects describing which objectives or educational standards this badge aligns to, if any.

Because of JSON-LD conventions, 
`[{"foo": "bar"}]` and `{"foo": "bar"}` are treated as equivalent. [See this JSON-LD playground](http://json-ld.org/playground/#/gist/000189cdf62199abe390b3773797c3b0)

The new [2.0 validator](https://github.com/openbadges/badgecheck/tree/develop) compacts retrieved BadgeClass JSON upon input, so if we get a single entry list, we'll validate it as `{"foo": "bar"}` without special configuration. I'll likely write an additional check to make sure this rule is honored.

I'm not proposing an urgent change... just something to consider for the workgroup to prioritize as it sees fit.

**Comment by ottonomy** [comment]
Same applies to `tags` ([link](https://openbadgespec.org/#tags))

|  property  |  type  |  rules  |
|-|-|-|
| tags | Array of Text | List of tags that describe the type of achievement. |

If a BadgeClass has a single tag like `"tags": ["tagOne"]`, and you run it through a JSON-LD "compact" operation, the output is `"tags": "tagOne"`. 

As a displayer, implementing support to handle these two cases as equivalent is the same as what you'd need to do if you implemented support for the `type` property, where the spec is explicit about the need for displayers to handle any valid JSON-LD single or multiple value.

**Comment by mgylling** [comment]
Fixed in #150
