### ISSUE TITLE
Add Image Attributions / Licenses

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#49]
Received a lot of feedback that this needs to be part of the specification. In _many_ cases badge creators are not using original images, but are pulling from icon libraries and other sources that use CC licenses that require attribution. 

Right now most of these badge creators are not adhering to the license by using these image resources or icons because they have no way to attribute the image.

Just noting this here for future work.

**Comment by timothyfcook** [comment]
From Standards call on 8/18: This might be especially important if we allow the duplication of badgeClasses. Then this concerns more than just the badge images, but also the license for the badge itself.

**Comment by ottonomy** [comment]
@timothyfcook: We've now acted on this (thanks for editorial advice). #68 contains a license extension. 

As of v1.1 this extension may be applied to a BadgeClass to cover its metadata and image in one go. If the Standard Working Group adopts, as I recommend, that Linked Data become the official data model of the OB Spec, then this could be used within an image declaration instead, if the desire would be to license only the image. However, I'd really recommend best practices just to license the whole BadgeClass and its associated resources at once (Criteria, Image).
