### ISSUE TITLE
Updates to BadgeAssertion and BadgeClass

### ISSUE THREAD

**Issue by cmcavoy** [openbadges/openbadges-specification#5]
### Fully formed `badge` property in BadgeAssertion

 Allow the `badge` property of the [BadgeAssertion](https://github.com/mozilla/openbadges-specification/blob/master/Assertion/latest.md#badgeassertion) to be either a URL pointing to a [BadgeClass](https://github.com/mozilla/openbadges-specification/blob/master/Assertion/latest.md#badgeclass) or a BadgeClass object presented inline.

*Why?* When a badge is baked in the Mozilla Backpack, the BadgeClass is added to the BadgeAssertion as a full formed object rather than a URL. It's a logical move, as we want as much information about the badge baked in as possible. We should allow this as an alternative in the hosted BadgeAssertion as well.

### Add `badgeclass_url` property to BadgeClass

Add `badgeclass_uri` as a required property to the `BadgeClass`. The URI could be a hosted URL that includes the BadgeClass, or a unique URI that uniquely identifies the BadgeClass

*Why?* BadgeClasses need a uri to allow for disambiguation between different BadgeClasses. Something to note - it's a uri, not a url, there's no obligation to actually host the BadgeClass in this proposal. I'd like to be able to issue a badge without hosting any files, or minimally hosting a public key and signing the badge. That said, this proposal _does not include_ the removal of `criteria` as a required property of the BadgeClass.

### Fully formed `issuer` property of BadgeClass

Allow the `issuer` property of the BadgeClass to be a URL pointer or a fully formed object.

 *Why?* Similar to the above, want to allow the badge to include as much information as possible in the BadgeAssertion

### Discussion

Discussion for this proposal can occur in this thread, or on the [ba-standard working group mailing list](https://groups.google.com/forum/#!forum/ba-standard). This proposal is posted on the [ba-standard working group proposals page](http://wiki.badgealliance.org/index.php/Ba-standard-proposals) and to the working group mailing list. A courtesy cross post is on the [Open Badges discussion list](https://groups.google.com/forum/#!forum/openbadges) and [Open Badges dev list](https://groups.google.com/forum/#!forum/openbadges-dev).

**Comment by ottonomy** [comment]
The above comment doesn't reflect current thinking in the Standard Working Group anymore. The original structure from `v0.5` is still semantically accurate: `{ Assertion { BadgeClass { Issuer } } }`, but a number of contributors are proposing that the `issuer` property be allowed in the Assertion as well as the BadgeClass to indicate when a different organization is the awarder of a credential than the one that defined it.
```json
{
  "type": "Assertion",
  "badge": {
    "type": "BadgeClass",
    "issuer": { "type": "Issuer" }
  },
  "issuer": { "type": "Issuer" }
}
```

I lean toward not including this change with `v2.0`, but waiting until v2.1 to do it. By then, the Issuer class will have a publicKey attribute, and we'll have a revamped endorsement procedure, so cryptographic signing of Assertions will be significantly more robust, and we can define rules for when a third party organization is trusted by the issuer to award credentials defined by the issuer.

**Comment by timothyfcook** [comment]
Splitting this ticket out into a couple new more discrete tickets.

**Comment by ottonomy** [comment]
Thanks, @timothyfcook for porting these capabilities over to issue #82. Closing this one now.
