### ISSUE TITLE
Profile Question

### ISSUE THREAD

**Issue by kayaelle** [openbadges/openbadges-specification#504]
Profile mentions that it could be used to represent recipients:

https://1edtech.github.io/openbadges-specification/ob_v3p0.html#profile

What's the best way to include it in the credentialSubject or AchievementSubject?

**Comment by amiller-ims** [comment]
The language is a little confusing. The `recipient` in OB 2.0 and the `credentialSubject` in OB 3.0 can be identified with an `IdentityObject`. The OB 2.0 `IdentityObject.type` property specified the type of the `IdentityObject.identity` property. For example, "email". In OB 3.0, the `IdentityObject.identityType` property serves the same purpose, but is no longer limited to the Profile namespace.

I think the OB 3.0 description of the Profile object should be updated. It uses many OB 2.0 terms that are no longer appropriate.
