### ISSUE TITLE
Develop Methods for Version Control and Changes to badgeClasses

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#53]
From Standards call on 8/18/2015:

Changes to hosted badge objects: consequences and best practices

Use-cases:
1. Internally within organizations: year-to-year qualitative improvements to the badge, keeping track of the history behind the badge's development while pointing back to its origination so that consumers of the badge would count both new and old versions of the badge within pathways, etc.
2. Externally between organizations when badges are shared and remixed by other organizations.

The solution could easily address both use-cases if it referenced:
- the diff between the new/old badge data
- the author of the new version (versus the previous version)
- date of the change

Outstanding questions:
- how do you reference previous versions? Do we archive all old versions and host those separate badgeClass end-points indefinitely? Do we overwrite them, but include the old badgeClass information (at least the diffs) as a buried extension with the new badgeClass?

@ottonomy says we should write a whitepaper to define best practices and inform future specification development.

**Comment by szerge** [comment]
One use case could be PD: you earned that badge version 1.0, now the requirements have changed to 1.5, you're invited to upgrade and/or get verified.

**Comment by timothyfcook** [comment]
## User Stories:

1. As a creator or issuer of a badge, I want to make year-to-year qualitative improvements to the badge and keep track of the history behind the badge's development so that consumers of the badge can understand its history.
2. As an issuer or remixer of a badge, I want to keep track of the history of the badges development across multiple collaborators so that I can credit all contributors and allow recipients to understand the history behind the badge.
3. As a consumer of badges, I want to understand when two Assertions with differing BadgeClasses represent two different versions of the same achievement as opposed to two distinct achievements, so that I can properly relate them.

**Comment by kayaelle** [comment]
This issue is for badge class only? Issuer object as well, but not assertion, right? 

CTI is hosting badge class data and are versioning. May be able to lean on this system some. Otherwise, could have an array of references (links?) to previous versions. More unwieldy would be inserting diffs for each version especially if we're considering embedding criteria data.

**Comment by ottonomy** [comment]
👍 @kayaelle. I've heard a couple references to this on the CTI meeting today. We should collaborate on vocabulary, and at try to use the same. Probably diffs would be too heavyweight.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
