### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by SueSmith** [openbadges/openbadges-specification#6]
Started redrafting spec docs here: https://github.com/mozilla/openbadges-specification/blob/doc-links/Assertion/latest.md

Keeping an eye on these:
* #5 
* https://github.com/mozilla/openbadges-discussion/pull/21 
* https://github.com/mozilla/openbadges-discussion/issues/20 
...will update accordingly. If I've missed any relevant issues please let me know.. 

On the existing spec repo readme I see there's a "TODO" for a backpack page - can I ask what that would cover? If I can draft something for it let me know.. wondering if https://github.com/mozilla/badgekit-backpack be the main source..?

Is there anything else that should be on the spec repo? Something about badge directories maybe?

cc @cmcavoy @threeqube

**Comment by ottonomy** [comment]
I think most of these issues have been resolved or are no longer relevant. Feel free to reopen or refile if that is incorrect.

**Comment by threeqube** [comment]
:+1:
