### ISSUE TITLE
Issuing a statement of endorsement to a BadgeClass

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#73]
**User Stories for BadgeClass Endorsement:** 
- As an issuer of a BadgeClass, I want to have third-parties endorse my BadgeClass so that they can add value to it before I issue it to learners.  
- As a learner, I would like to search for BadgeClasses that are endorsed by organizations I respect so that I can find credential opportunities that are meaningful to me.
- As a learner, I want the badges I have earned to be respected by people I share them with, so I want them to be endorsed by respected organizations.

[Noted as a priority in the Open Badges use-cases document created by the community.](https://docs.google.com/document/d/1eT2QwSsLIOSLbG4x8-uWDC-knM7lwFrXsPPm__YVWOM/edit#heading=h.2epgzbobbg40)

**Comment by timothyfcook** [comment]
Should call out the fine line between these two:

- As an important certifying organization I authorize a smaller organization to issue a badgeClass I've created
- As an important certifying organization I endorse a badgeClass issued by a smaller organization

These two implementations have nearly the same result, but different timelines and options.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
