### ISSUE TITLE
Insert Criteria into a BadgeClass definition

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#74]
## User Stories:
- As an issuer, I want to be more clear about my badge's criteria by including the BadgeClass metadata directly as well as linking to a URL on my website where the information is formatted for human readers.
- As an issuer, I want to define a BadgeClass without creating an external criteria URL, so I would like to define it solely in machine-readable metadata embedded in the BadgeClass.
- As a badge recipient, I would like detailed criteria to appear within the badge metadata and alongside the descriptions of the badges I have earned so that when I share them, consumers can see the badge criteria without having to visit an external site.

[Noted as a priority in the use-cases document created by the community.](https://docs.google.com/document/d/1eT2QwSsLIOSLbG4x8-uWDC-knM7lwFrXsPPm__YVWOM/edit#heading=h.193axowyf3q4)

**Comment by szerge** [comment]
c.f. solution suggested in issue #81...

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
