### ISSUE TITLE
Issuing a statement of endorsement to a badgeAssertion

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#76]
**User Stories for BadgeAssertion Endorsement:**
- As a recipient of an Assertion indicating my skill, I would like the people who have worked with me to validate that Assertion by endorsing it.
- As a recipient, I want the people I work with to be able to endorse my existing badges, so that I can continually add to and validate my earned credentials over time.

**Comment by ottonomy** [comment]
When we consider the implementation of endorsement for BadgeClasses and for Assertions, we may consider that the implementation will be identical to endorsing Issuer/Recipient Profiles and/or any other Linked Data subject. See also #73

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
