### ISSUE TITLE
Update Recipient Class to allow for expanded identity types

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#77]
Currently the recipient class only allows for the `email` identity type, this makes it difficult to issue badges to entities that are not easily identified by a single email address, or difficult to align badges to an identity if their email address changes.
### User Stories
1. As an organization or an individual, I want to define and be identified by a public hosted **Profile** that includes any number of attributes and to have badges issued to that profile so that my public profile can establish credibility.
2. As an organization or individual, I want to issue badges to a recipient's profile that can contain multiple identifiers so that I can add to the credibility these profiles have established using one or more of their identifiers.
3. As an organization or an individual, I want to issue badges from my public profile so that recipients and consumers of my badges can more fully understand who awarded this badge.
4. As an issuer, I want to define a profile based on any number of attributes for a recipient who has not yet created their own profile on my system, so that I can quickly award badges to that individual.
5. As an issuer, I would like to award a badge to a recipient based on hashed (obscured) versions of attributes that identify them so that inspectors are not easily able to discover the recipient's identity, while enabling the badge to be reconciled with public versions of the recipient's profile.

Note: By "Profile", we mean a publicly hosted end-point offering a set of properties defining an entity. The ownership of this profile is controlled by the individual or organization that it describes.

**Comment by ottonomy** [comment]
@timothyfcook and I started some draft work here: https://usecanvas.com/ottonomy/open-badges-20-recipient-profile-object/5EcyEgVnZKL26o46Cw7cTN

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
