### ISSUE TITLE
Verify Authenticity of the Issuer reference in a badge

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#78]
### User Stories
- As a badge consumer, I want to verify that the badge was awarded by the expected issuer Profile, so that I can ensure its authenticity.
  - Note: this does not verify that the identity of the issuer Profile is authentic, but completes the first step to verify that the issuer profile referenced in the BadgeClass and/or Assertion was truly the creator of the BadgeClass.
- As a badge consumer, I want to verify that the badge was awarded to the expected recipient Profile, so that I can ensure its authenticity.

**Comment by 1l2p** [comment]
This seems easier to implement through the use of a blockchain or other ledger that maintains a list of badge issuing transactions. Identity can be represented by a set of public addresses, controlled by the issuer and the recipient respectively.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
