### ISSUE TITLE
Verifying an entity corresponds to a specific Profile

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#79]
**Problem/challenge**: Verifying that the entity presenting a badge to you is an entity referenced in the badge is a challenge. This can be done prior to issuing the badge (issuer checks the recipient) when receiving the badge (earner checks the issuer) and post issue (the consumer verifies the recipient and issuer).

**Requirement**: Profiles must contain properties that are possible to verify through interactive processes that scale. A consumer must be able to verify that a defined Profile corresponds to properties it can trust belongs to a particular entity, whether that is a logged in user, a person, or an organization.

**Motivation**: To enable a more expressive vocabulary for defining issuers and recipients of badges, the ability to verify different identifying properties of a profile on a broad scale becomes more important.

**User Stories**:
1. As a badge consumer, earner, or issuer, I want to verify that a profile truly corresponds to its stated entity so that I can trust badge claims related to that profile.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
