### ISSUE TITLE
Verify the expiration and revocation status of the badge

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#80]
### User Stories
- As a badge consumer, I want to verify the expiration status of a badgeAssertion, so that I can trust its claims about the recipient remain valid.
- As a badge consumer, I want to verify that a badgeAssertion has not been revoked by its issuer, so that I can trust its claims about the recipient remain valid.

**Comment by kayaelle** [comment]
Not sure I understand this issue. What more needs to be done with expiration date? Think other revocation issues cover user story #2.

**Comment by ottonomy** [comment]
@kayaelle This story just covers capabilities that essentially already exist in the specification. Some work is necessary to update the descriptions of the procedure(s) for checking expiration and revocation.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
