### ISSUE TITLE
Enforce specific syntax for timestamp

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#86]
### User Story:

As a badge issuing platform, I would like all badges to use a common timestamp format, so that I know specificity will be consistent, and I can limit the number of code libraries I need to leverage to understand badges.

**Comment by ottonomy** [comment]
I will take an action to develop a proposal for this story in the next 2 weeks.

**Comment by ottonomy** [comment]
Proposal:

All timestamps used in badges SHOULD be ISO-8601 timestamps that include a time value in UTC (Z).

The key word "SHOULD" in this document are to be interpreted as described in RFC 2119

**Comment by ottonomy** [comment]
This feature did not gain strong buy-in from participants to the 2.0 prioritization poll. 

I think we should include it as a SHOULD statement, and then in the validators, provide translation of other values to this format.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
