### ISSUE TITLE
Update the Identity of a Recipient

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#88]
### User Stories:
1. As a recipient of a badge, I want to request that issuers update the identity information on my badge assertions so that I can prove ownership of my badges in perpetuity.
2. As a recipient of a badge, I want to provide evidence of ownership of my badges in perpetuity even if my identity information originally referenced in those badges becomes deprecated.
3. As a badge issuer, I want to update the recipient profile of a previously issued Assertion, so that recipients of my badges can easily use these badges, even if they change email addresses or lose the ability to verify a previously used identifier.

**Comment by kayaelle** [comment]
re: #1 & #2 - previous identity information should be accessible along with updated information. Possibly do this by issuing a new badge that references the previous one noting the change in identity.

**Comment by ottonomy** [comment]
@kayaelle I definitely prefer an approach that doesn't rely on updating a previous resource. Instead, creating a new resource that provides a change to the old is my preferred method. This ticket outlines an alternate approach.

**Comment by ottonomy** [comment]
4. As a badge issuer, I want to endorse a recipient profile to say that all badges I have awarded to another specific identifier/profile may be considered as awarded to the endorsed profile.

This is a more complicated use case than the three in the initial post. But it doesn't require a modification/reissue of an Assertion, which is a big advantage, especially as we move toward widespread signed assertions.

**Comment by 1l2p** [comment]
Most of the use cases seem easier to handle through a simple reissue (and revocation of previous badge), and can be negotiated between recipient and issuer.

**Comment by kayaelle** [comment]
It is a decent case for revocation. I'm against changing badge data without a history. Not against adding data to badges. Perhaps this is a case for an extension that is considered an add-on post-issuance? This would be easier on the earner and consumer than revocation and reissue.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
