### ISSUE TITLE
Reference public key in profile instead of assertion

### ISSUE THREAD

**Issue by ottonomy** [openbadges/openbadges-specification#89]
1. As a badge Issuer and Recipient, I would like to reference my public key in my Profile, so that I can be easily associated with it.
2. As a consumer of badges, I want to verify signed badges against a public key referenced in the Issuer Profile, not one referenced in the Assertion, so that I can trust the badge was signed by the issuer Profile I expect.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
