### ISSUE TITLE
Non-technical Description of Specification

### ISSUE THREAD

**Issue by jbohrer** [openbadges/openbadges-specification#96]
1. As a non-programmer badge issuer or recipient, I would like an easy-to-understand description of the Open Badges specification so that I can understand the underlying Badge Objects and properties through narrative and examples.

**Comment by ottonomy** [comment]
https://openbadgespec.org/faq/ Have you taken a look at this page? Does it do a complete enough job?

**Comment by jbohrer** [comment]
I've been awaiting feedback and further requirements on this issue from the original requestor. Lacking the feedback right now, I suggest closing this issue pending further clarification.
